baseurl:
google_tracking_id: UA-3769691-29
exclude:
  - config.ru
  - Rakefile
  - gems
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - ".gitignore"
  - CONTRIBUTING.md
  - vendor/
  - script/
markdown: kramdown
kramdown:
  auto_ids:     false

jekyll_auth:
  ssl: true

gems:
  - jekyll-geo-pattern
  - jekyll-redirect-from
  - jemoji
  - jekyll-avatar

organization:
  - /introduction/flow/
  - /activities/hello-world/
  - /activities/contributing-to-open-source/
  - /features/pages/
  - /introduction/getting-your-project-on-github/
  - /activities/forking/
  - /activities/socialize/
  - /activities/citable-code/
  - /features/issues/
  - /features/mastering-markdown/
  - /features/wikis/
