baseurl:
google_tracking_id: UA-3769691-29
exclude:
  - gems
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - ".gitignore"
  - CONTRIBUTING.md
markdown: rdiscount
rdiscount:
  extensions: [smart]

gems:
  - jekyll-geo-pattern
  - jekyll-redirect-from
  - jemoji

organization:
  - /introduction/flow/index.html
  - /activities/hello-world/index.html
  - /activities/contributing-to-open-source/index.html
  - /features/pages/index.html
  - /introduction/getting-your-project-on-github/index.html
  - /activities/forking/index.html
  - /activities/socialize/index.html
  - /activities/citable-code/index.html
  - /features/issues/index.html
  - /features/mastering-markdown/index.html
  - /features/wikis/index.html
