title: "திறந்த மூல வழிகாட்டிகள்"
description: "உங்கள் திட்டத்தை எவ்வாறு தொடங்குவது மற்றும் வளர்வது என்பதை அறிக."

# See: docs/translations.md
locale: ta-IN
translations:
  en-US:
    name: English (US)
    url: https://opensource.guide

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor
  - node_modules

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

sass:
  style: :compressed
  sass_dir: assets/css/
  load_paths:
    - node_modules

branch: gh-pages

github:
  repository_nwo: github/opensource.guide

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/
