baseurl: "/open-source-handbook"

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor

permalink: /:path/

collections:
  faqs:
    output: true
    permalink: /faq/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: article

gems:
  - jekyll-mentions
  - jekyll-octicons

branch: gh-pages

github:
  repository_nwo: github/open-source-handbook
