title: "Open Source Handbook"
description: "A community handbook for open source creators."

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: article

gems:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap
  
branch: gh-pages

github:
  repository_nwo: github/open-source-handbook

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/
