baseurl:
google_tracking_id: UA-3769691-29
exclude:
  - gems
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - ".gitignore"
  - CONTRIBUTING.md
  - vendor/
markdown: kramdown
kramdown:
  input:        GFM
  auto_ids:     false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

gems:
  - jekyll-geo-pattern
  - jekyll-redirect-from
  - jemoji

organization:
  - /introduction/flow/
  - /activities/hello-world/
  - /activities/contributing-to-open-source/
  - /features/pages/
  - /introduction/getting-your-project-on-github/
  - /activities/forking/
  - /activities/socialize/
  - /activities/citable-code/
  - /features/issues/
  - /features/mastering-markdown/
  - /features/wikis/
