name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      - name: Bootstrap
        run: script/bootstrap
        env:
          SKIP_BUNDLER: true
      - name: Tests
        run: script/test
