name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: [snyk-fix-48104f3a897962eaf3bbd20d78350ea2]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1

    - name: Set up Node
      uses: actions/setup-node@v1

    - name: Restore bundler cache
      uses: actions/cache@v1
      with:
        path: vendor/gems
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-

    - name: Bootstrap
      run: script/bootstrap

    - name: Tests
      run: script/test
